#loc_city = ""                   # Enter your city name (this is for the weather)
#loc_region = ""                # Enter either your state or country
weather_location = ""
news_count = 2                        # How many news stories Vector should read (max is 7 to 9)
vector_mood = "normal"                # Normal is the only mood at the moment
temperature = "imperial"             # Enter "imperial" or "metric"
chattiness = 6                        # Enter a number between "1" and "10". The number "5" is average. ("10" is VERY chatty.) This feature still needs work.
sound_volume = 1                      # Vector's sound effects between "1" and "5". (5 is very loud)
voice_volume = 3                      # Vector's voice volume between "1" and "5". (5 is very loud)
news_feed = "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"   #I think you can use any rss feed for this